# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\CENGİZ\Desktop\PhytonCalismalarim\Tasarimlarim\MasterCelebi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 710)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 640, 360))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setMaximumSize(QtCore.QSize(2200, 2200))
        self.mdiArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mdiArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.mdiArea.setDocumentMode(True)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setObjectName("mdiArea")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 21))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menuAra_lar = QtWidgets.QMenu(self.menubar)
        self.menuAra_lar.setObjectName("menuAra_lar")
        self.menuHakk_nda = QtWidgets.QMenu(self.menubar)
        self.menuHakk_nda.setObjectName("menuHakk_nda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_HesapMakinesi = QtWidgets.QAction(MainWindow)
        self.menu_HesapMakinesi.setObjectName("menu_HesapMakinesi")
        self.action_k = QtWidgets.QAction(MainWindow)
        self.action_k.setObjectName("action_k")
        self.menuDosya.addAction(self.action_k)
        self.menuAra_lar.addAction(self.menu_HesapMakinesi)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuAra_lar.menuAction())
        self.menubar.addAction(self.menuHakk_nda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Çelebi MDI Form Örneği"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.menuAra_lar.setTitle(_translate("MainWindow", "Araçlar"))
        self.menuHakk_nda.setTitle(_translate("MainWindow", "Hakkında"))
        self.menu_HesapMakinesi.setText(_translate("MainWindow", "Hesap Makinesi"))
        self.action_k.setText(_translate("MainWindow", "Çıkış"))
